### ISSUE TITLE
RepoRobot constantly complains too many files, doesn't allow PR

### ISSUE THREAD

**Issue by SongGithub** [jlord/patchwork#11101] opened 2016-05-11 11:28 UTC
Hi Jessica, 

I am doing a PR #11099 and #11086, but the robot doesn't allow me the PR on bases that there are too many files other than add-USERNAME. 

I am confused, hence I have deleted all the files except the add-USERNAME in Contributor folder. Then the robot keeps complaining "too many files"

**Comment by jlord** [comment] 2016-05-14 22:49
Yeah it shows you have _all_ 8,000+ files in your pull request. I'm not sure why, I've asked others too and unfortunately don't have an answer for you. If you're up for it, my only suggestion is to re-clone the repository and start over 😓

**Comment by jlord** [comment] 2016-05-14 22:52
Closing as a dupe of #8929

**Closed as completed by jlord** 2016-05-14 22:52 UTC
