### ISSUE TITLE
reporobot doesn't accept invitation

### ISSUE THREAD

**Issue by Traci7822** [jlord/patchwork#13952] opened 2016-09-01 02:17 UTC
**NOTE** I do not get notifications for new issues created in this repository (because there are so many PRs coming through as people do the challenges it would flood my inbox) so if you open an issue you must ping me, @jlord. 

Also please consider if your issue is actually with [Git-it](https://github.com/jlord/git-it-electron) or [reporobot](https://github.com/jlord/reporobot) as this repository is generated by those two.

**Comment by jlord** [comment] 2016-09-01 22:41
Hi! You haven't added any context to your issue here but I'm guessing you're referring to https://github.com/jlord/patchwork/issues/11760 about the change in GitHub's repo invites breaking part of @reporobot.

I'll close this here as it's a dupe of the issue I mentioned above (I've also noted it in the Git-it repo as an issue and on the remade). Also I'm in the process of fixing it so it'll be working 🔜 if it isn't already 😄

**Closed as completed by jlord** 2016-09-01 22:41 UTC
